// Generated by gencpp from file computer_pkg/PlaceSensor.msg
// DO NOT EDIT!


#ifndef COMPUTER_PKG_MESSAGE_PLACESENSOR_H
#define COMPUTER_PKG_MESSAGE_PLACESENSOR_H

#include <ros/service_traits.h>


#include <computer_pkg/PlaceSensorRequest.h>
#include <computer_pkg/PlaceSensorResponse.h>


namespace computer_pkg
{

struct PlaceSensor
{

typedef PlaceSensorRequest Request;
typedef PlaceSensorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlaceSensor
} // namespace computer_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::computer_pkg::PlaceSensor > {
  static const char* value()
  {
    return "92d27cc93d35e7c5066371f928a11ffc";
  }

  static const char* value(const ::computer_pkg::PlaceSensor&) { return value(); }
};

template<>
struct DataType< ::computer_pkg::PlaceSensor > {
  static const char* value()
  {
    return "computer_pkg/PlaceSensor";
  }

  static const char* value(const ::computer_pkg::PlaceSensor&) { return value(); }
};


// service_traits::MD5Sum< ::computer_pkg::PlaceSensorRequest> should match
// service_traits::MD5Sum< ::computer_pkg::PlaceSensor >
template<>
struct MD5Sum< ::computer_pkg::PlaceSensorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::computer_pkg::PlaceSensor >::value();
  }
  static const char* value(const ::computer_pkg::PlaceSensorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::computer_pkg::PlaceSensorRequest> should match
// service_traits::DataType< ::computer_pkg::PlaceSensor >
template<>
struct DataType< ::computer_pkg::PlaceSensorRequest>
{
  static const char* value()
  {
    return DataType< ::computer_pkg::PlaceSensor >::value();
  }
  static const char* value(const ::computer_pkg::PlaceSensorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::computer_pkg::PlaceSensorResponse> should match
// service_traits::MD5Sum< ::computer_pkg::PlaceSensor >
template<>
struct MD5Sum< ::computer_pkg::PlaceSensorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::computer_pkg::PlaceSensor >::value();
  }
  static const char* value(const ::computer_pkg::PlaceSensorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::computer_pkg::PlaceSensorResponse> should match
// service_traits::DataType< ::computer_pkg::PlaceSensor >
template<>
struct DataType< ::computer_pkg::PlaceSensorResponse>
{
  static const char* value()
  {
    return DataType< ::computer_pkg::PlaceSensor >::value();
  }
  static const char* value(const ::computer_pkg::PlaceSensorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMPUTER_PKG_MESSAGE_PLACESENSOR_H
