// Generated by gencpp from file drone_pkg/DroneOpRequest.msg
// DO NOT EDIT!


#ifndef DRONE_PKG_MESSAGE_DRONEOPREQUEST_H
#define DRONE_PKG_MESSAGE_DRONEOPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drone_pkg
{
template <class ContainerAllocator>
struct DroneOpRequest_
{
  typedef DroneOpRequest_<ContainerAllocator> Type;

  DroneOpRequest_()
    : mode(0)  {
    }
  DroneOpRequest_(const ContainerAllocator& _alloc)
    : mode(0)  {
  (void)_alloc;
    }



   typedef int32_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::drone_pkg::DroneOpRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_pkg::DroneOpRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DroneOpRequest_

typedef ::drone_pkg::DroneOpRequest_<std::allocator<void> > DroneOpRequest;

typedef boost::shared_ptr< ::drone_pkg::DroneOpRequest > DroneOpRequestPtr;
typedef boost::shared_ptr< ::drone_pkg::DroneOpRequest const> DroneOpRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_pkg::DroneOpRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_pkg::DroneOpRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drone_pkg::DroneOpRequest_<ContainerAllocator1> & lhs, const ::drone_pkg::DroneOpRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drone_pkg::DroneOpRequest_<ContainerAllocator1> & lhs, const ::drone_pkg::DroneOpRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drone_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::drone_pkg::DroneOpRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_pkg::DroneOpRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_pkg::DroneOpRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_pkg::DroneOpRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_pkg::DroneOpRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_pkg::DroneOpRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_pkg::DroneOpRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff63f6ea3c3e9b7504b2cb3ee0a09d92";
  }

  static const char* value(const ::drone_pkg::DroneOpRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff63f6ea3c3e9b75ULL;
  static const uint64_t static_value2 = 0x04b2cb3ee0a09d92ULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_pkg::DroneOpRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_pkg/DroneOpRequest";
  }

  static const char* value(const ::drone_pkg::DroneOpRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_pkg::DroneOpRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 mode\n"
;
  }

  static const char* value(const ::drone_pkg::DroneOpRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_pkg::DroneOpRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DroneOpRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_pkg::DroneOpRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone_pkg::DroneOpRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_PKG_MESSAGE_DRONEOPREQUEST_H
