// Generated by gencpp from file drone_pkg/DroneOp.msg
// DO NOT EDIT!


#ifndef DRONE_PKG_MESSAGE_DRONEOP_H
#define DRONE_PKG_MESSAGE_DRONEOP_H

#include <ros/service_traits.h>


#include <drone_pkg/DroneOpRequest.h>
#include <drone_pkg/DroneOpResponse.h>


namespace drone_pkg
{

struct DroneOp
{

typedef DroneOpRequest Request;
typedef DroneOpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DroneOp
} // namespace drone_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::drone_pkg::DroneOp > {
  static const char* value()
  {
    return "46e3fbb42467cdb3ed60e9a1d6e7dbc3";
  }

  static const char* value(const ::drone_pkg::DroneOp&) { return value(); }
};

template<>
struct DataType< ::drone_pkg::DroneOp > {
  static const char* value()
  {
    return "drone_pkg/DroneOp";
  }

  static const char* value(const ::drone_pkg::DroneOp&) { return value(); }
};


// service_traits::MD5Sum< ::drone_pkg::DroneOpRequest> should match
// service_traits::MD5Sum< ::drone_pkg::DroneOp >
template<>
struct MD5Sum< ::drone_pkg::DroneOpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::drone_pkg::DroneOp >::value();
  }
  static const char* value(const ::drone_pkg::DroneOpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::drone_pkg::DroneOpRequest> should match
// service_traits::DataType< ::drone_pkg::DroneOp >
template<>
struct DataType< ::drone_pkg::DroneOpRequest>
{
  static const char* value()
  {
    return DataType< ::drone_pkg::DroneOp >::value();
  }
  static const char* value(const ::drone_pkg::DroneOpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::drone_pkg::DroneOpResponse> should match
// service_traits::MD5Sum< ::drone_pkg::DroneOp >
template<>
struct MD5Sum< ::drone_pkg::DroneOpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::drone_pkg::DroneOp >::value();
  }
  static const char* value(const ::drone_pkg::DroneOpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::drone_pkg::DroneOpResponse> should match
// service_traits::DataType< ::drone_pkg::DroneOp >
template<>
struct DataType< ::drone_pkg::DroneOpResponse>
{
  static const char* value()
  {
    return DataType< ::drone_pkg::DroneOp >::value();
  }
  static const char* value(const ::drone_pkg::DroneOpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRONE_PKG_MESSAGE_DRONEOP_H
