// Generated by gencpp from file computer_pkg/PlaceSensorRequest.msg
// DO NOT EDIT!


#ifndef COMPUTER_PKG_MESSAGE_PLACESENSORREQUEST_H
#define COMPUTER_PKG_MESSAGE_PLACESENSORREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace computer_pkg
{
template <class ContainerAllocator>
struct PlaceSensorRequest_
{
  typedef PlaceSensorRequest_<ContainerAllocator> Type;

  PlaceSensorRequest_()
    : latitude(0.0)
    , longitude(0.0)
    , battery(0.0)  {
    }
  PlaceSensorRequest_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)
    , battery(0.0)  {
  (void)_alloc;
    }



   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef float _battery_type;
  _battery_type battery;





  typedef boost::shared_ptr< ::computer_pkg::PlaceSensorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::computer_pkg::PlaceSensorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlaceSensorRequest_

typedef ::computer_pkg::PlaceSensorRequest_<std::allocator<void> > PlaceSensorRequest;

typedef boost::shared_ptr< ::computer_pkg::PlaceSensorRequest > PlaceSensorRequestPtr;
typedef boost::shared_ptr< ::computer_pkg::PlaceSensorRequest const> PlaceSensorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::computer_pkg::PlaceSensorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::computer_pkg::PlaceSensorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::computer_pkg::PlaceSensorRequest_<ContainerAllocator1> & lhs, const ::computer_pkg::PlaceSensorRequest_<ContainerAllocator2> & rhs)
{
  return lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.battery == rhs.battery;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::computer_pkg::PlaceSensorRequest_<ContainerAllocator1> & lhs, const ::computer_pkg::PlaceSensorRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace computer_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::computer_pkg::PlaceSensorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::computer_pkg::PlaceSensorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::computer_pkg::PlaceSensorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::computer_pkg::PlaceSensorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::computer_pkg::PlaceSensorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::computer_pkg::PlaceSensorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::computer_pkg::PlaceSensorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fad2e88560e107354b953b24a23d72d5";
  }

  static const char* value(const ::computer_pkg::PlaceSensorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfad2e88560e10735ULL;
  static const uint64_t static_value2 = 0x4b953b24a23d72d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::computer_pkg::PlaceSensorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "computer_pkg/PlaceSensorRequest";
  }

  static const char* value(const ::computer_pkg::PlaceSensorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::computer_pkg::PlaceSensorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 latitude\n"
"float64 longitude\n"
"float32 battery\n"
;
  }

  static const char* value(const ::computer_pkg::PlaceSensorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::computer_pkg::PlaceSensorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.battery);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlaceSensorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::computer_pkg::PlaceSensorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::computer_pkg::PlaceSensorRequest_<ContainerAllocator>& v)
  {
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "battery: ";
    Printer<float>::stream(s, indent + "  ", v.battery);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMPUTER_PKG_MESSAGE_PLACESENSORREQUEST_H
