// Generated by gencpp from file drone_pkg/DroneOpResponse.msg
// DO NOT EDIT!


#ifndef DRONE_PKG_MESSAGE_DRONEOPRESPONSE_H
#define DRONE_PKG_MESSAGE_DRONEOPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drone_pkg
{
template <class ContainerAllocator>
struct DroneOpResponse_
{
  typedef DroneOpResponse_<ContainerAllocator> Type;

  DroneOpResponse_()
    : success(false)  {
    }
  DroneOpResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::drone_pkg::DroneOpResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_pkg::DroneOpResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DroneOpResponse_

typedef ::drone_pkg::DroneOpResponse_<std::allocator<void> > DroneOpResponse;

typedef boost::shared_ptr< ::drone_pkg::DroneOpResponse > DroneOpResponsePtr;
typedef boost::shared_ptr< ::drone_pkg::DroneOpResponse const> DroneOpResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_pkg::DroneOpResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_pkg::DroneOpResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drone_pkg::DroneOpResponse_<ContainerAllocator1> & lhs, const ::drone_pkg::DroneOpResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drone_pkg::DroneOpResponse_<ContainerAllocator1> & lhs, const ::drone_pkg::DroneOpResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drone_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::drone_pkg::DroneOpResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_pkg::DroneOpResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_pkg::DroneOpResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_pkg::DroneOpResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_pkg::DroneOpResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_pkg::DroneOpResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_pkg::DroneOpResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::drone_pkg::DroneOpResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_pkg::DroneOpResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_pkg/DroneOpResponse";
  }

  static const char* value(const ::drone_pkg::DroneOpResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_pkg::DroneOpResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::drone_pkg::DroneOpResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_pkg::DroneOpResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DroneOpResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_pkg::DroneOpResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone_pkg::DroneOpResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_PKG_MESSAGE_DRONEOPRESPONSE_H
